- cmd/root.go
- draw.go
- keybind.go
- model.go
- move.go
- oviewer.go
- search.go
> Added columnMode

- internal/oviewer/model.go
Fixed the style reset procedure,
as continuous escape sequences were not enabled.
> Fixed ansi escape sequence parser

- internal/oviewer/draw.go
- internal/oviewer/keybind.go
- internal/oviewer/oviewer.go
Added input mode so that the tab width can be changed
even after startup.
> Changed so that the tab width can be changed dynamically

- internal/oviewer/draw.go
- internal/oviewer/input.go
- internal/oviewer/keybind.go
- internal/oviewer/oviewer.go
- internal/oviewer/search.go
- main.go
Display input candidates with the up and down cursor keys
when inputting.
> Add input candidates

- internal/oviewer/input.go
- internal/oviewer/keybind.go
- internal/oviewer/oviewer.go
Integrated mark and line number move.
Changed set method to argument instead of input.value.
> Move to the place marked

- oviewer/document.go
- oviewer/document_test.go
- oviewer/event.go
- oviewer/input.go
- oviewer/keybind.go
- oviewer/oviewer.go
Change multiple files to create each document.
Supported multiple documents in oviewer.
Added key bindings for document switching ](next) and [(prev).
> Open multiple files in each document

- oviewer/draw.go
- oviewer/event.go
- oviewer/input.go
- oviewer/keybind.go
- oviewer/move.go
- oviewer/oviewer.go
- oviewer/search.go
Added document for error log and debug log.
Logdoc can be switched and displayed like help.
> Added document for log

- oviewer/content.go
- oviewer/content_test.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/input.go
- oviewer/keybind.go
- oviewer/mouse.go
- oviewer/move.go
- oviewer/oviewer.go
- oviewer/reader.go
- oviewer/search.go
Abolished bcw.
Changed lineContents from a struct to an array of contents only.
> Refactor and simplify

- oviewer/keybind.go
- oviewer/mouse.go
- oviewer/oviewer.go
Supported switching between enable/disable of mouse by key.
> Added rectangular mode to mouse selection

- go.mod
- go.sum
- main.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/mouse.go
- oviewer/oviewer.go
- oviewer/search.go
Allow ctrl+c to cancel search.
Changed the signal catch method.
> Add search cancellation

- oviewer/document.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/move.go
- oviewer/oviewer.go
It was wrong if there was a header.
> Fixed the calculation starting in the middle of the line

- main.go
- ov.yaml
- oviewer/content_test.go
- oviewer/draw.go
- oviewer/oviewer.go
Enabled to specify style instead of color specification.
Search highlights and column highlights can also be specified.
> Changed style customization

- go.mod
- go.sum
- main.go
- oviewer/content.go
- oviewer/content_test.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/input.go
- oviewer/keybind.go
- oviewer/mouse.go
- oviewer/oviewer.go
Upgrade [tcell](https://github.com/gdamore/tcell) to v2.
> Upgrade tcell to v2

- oviewer/draw.go
- oviewer/move.go
Resolved #45.
Change the move to the bottom line.
Make the search line scrollable to the top of the screen.
However, the movement to the bottom is limited.
> Specification change of scroll like less

- oviewer/event.go
- oviewer/keybind.go
- oviewer/oviewer.go
Close the current document from multiple documents.
Adding documents is premised on using the library.
> Added event to add/close document

- main.go
- ov.yaml
- oviewer/document.go
- oviewer/oviewer.go
Fixed usage of cobra and viper.
Set the operation to general entry.
> Overwrite config with options

- oviewer/move.go
Fixed a mistake that was moving before the limit check.
> Fixed a mistake that was moving

- README.md
- ov-less.yaml
- ov.yaml
- oviewer/draw.go
- oviewer/oviewer.go
Enabled style customization of search and column highlights.
> Style customization is possible.

- oviewer/event.go
Change the interval event so that it does not wait.
PostEvent does not need goroutine.
> Change interval event to PostEvent

- oviewer/mouse.go
Improved from returning with bytes.Buffer to []bytes.
> Added some comments

- oviewer/action.go
- oviewer/document.go
- oviewer/oviewer.go
Todo: Closing a document needs to be delayed.
> Doesn't really close the Document

- oviewer/oviewer.go
screen.Init must be completed at the time of Run.
> Move screen.Init to NewOviewer

- oviewer/move.go
> Fixed a bug in moving when not in wrap Mode

- oviewer/move.go
> Fixed a bug of half down movement

- oviewer/document.go
- oviewer/oviewer.go
Don't block with select instead of channel capacity.
> Don't block channel with select

- .github/workflows/release.yml
- go.mod
- go.sum
- oviewer/oviewer.go
Fixed long wrapping lines producing more lines than the original.
> Consider wrap when writing the original

- main.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/input.go
- oviewer/oviewer.go
- oviewer/search.go
Incremental search can be enabled/disabled.
Search with goroutine.
Cancel when the next character is entered.
resolve #83
> Implement incremental search

- oviewer/draw.go
- oviewer/search.go
A non-regexp search word was not set.
> Fixed backsearch highlights

- oviewer/input.go
- oviewer/keybind.go
- oviewer/oviewer.go
- oviewer/search.go
Changed key bindings to be customizable.
> Changed the key binding when entering a search

- oviewer/event.go
- oviewer/search.go
- oviewer/search_test.go
searchword must remain the same while searching for goroutine.
Fix typo(regexpComile).
> Fixed race condition

- go.mod
- go.sum
- oviewer/help.go
- oviewer/keybind.go
- oviewer/oviewer.go
Moved help related functions to help.go.
Added heading modifiers.
Fixed the heading item.
> Improved help

- oviewer/move.go
It has been changed to not include skip-line.
> Fixed the calculation line in column mode

- oviewer/action.go
- oviewer/event.go
- oviewer/help.go
- oviewer/keybind.go
- oviewer/oviewer.go
- oviewer/sigtstp.go
- oviewer/sigtstp_windows.go
Supported suspend/resume because tcell suspend works.
It also suspends by signal.
Solved #5.
> Implemented suspend/resume

- go.mod
- go.sum
- oviewer/action.go
- oviewer/content.go
- oviewer/content_test.go
- oviewer/document.go
- oviewer/document_test.go
- oviewer/draw.go
- oviewer/mouse.go
- oviewer/move.go
- oviewer/oviewer.go
Change function name.
Add comment.
Improved the display of too many header specifications.
> Refactoring

- oviewer/action.go
- oviewer/draw.go
- oviewer/help.go
- oviewer/search.go
Add comment.
Swapping the code order.
Fixed header style reset mistake.
> Fixed lint indication

- go.mod
- go.sum
- oviewer/action.go
- oviewer/draw.go
- oviewer/move.go
- oviewer/oviewer.go
Stop pre-computing headerlen.
Saves the number of lines when drawing.
> Change the save timing of headerlen.

- main.go
- oviewer/exec.go
- oviewer/oviewer.go
- oviewer/reader.go
Enables standard output and standard error output like tee.
> Enable output like tee

- main.go
Fixed the wrong timing of defer and added a lap command.
> Fixed wrong timing of defer

- go.mod
- go.sum
- main.go
- oviewer/search_test.go
Also modified exec to return standard output and standard error.
> Also modified exec to return

- oviewer/move.go
- oviewer/search.go
- oviewer/search_test.go
Improved column mode to exclude columns
at both ends that have no value in the column.
> Column mode improvements

- main.go
- oviewer/keybind.go
- oviewer/oviewer.go
The redirect had to be set first.
Corrected the argument order of setHandler.
> Fixed a bad set of redirects

- go.mod
- go.sum
- oviewer/action.go
- oviewer/draw.go
- oviewer/move.go
- oviewer/oviewer.go
- oviewer/search.go
- oviewer/search_test.go
Changed to cache because it searches every time it moves.
Leftmostx cache stopped.
Enabled to specify a decimal point for line specification.
> Changed to cache search results

- oviewer/document.go
- oviewer/oviewer.go
- oviewer/reader.go
Changed to avoid seek failure of named pipe.
> Improved follow mode for named pipes

- oviewer/action.go
- oviewer/doclist.go
- oviewer/oviewer.go
- oviewer/utils.go
The doclist is in one file, because it involves a lock.
> Separate doclist related files

- oviewer/doclist.go
- oviewer/document.go
- oviewer/reader.go
Does not need to work immediately with close.
> Change closeCh to flag

- oviewer/action.go
- oviewer/document.go
- oviewer/event.go
- oviewer/exec.go
- oviewer/keybind.go
- oviewer/reader.go
Close the file, though it keeps the file open when in follow mode.
> Added action to close and reload file

- go.mod
- go.sum
- main.go
- oviewer/action.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/help.go
- oviewer/input.go
- oviewer/keybind.go
- oviewer/logdoc.go
- oviewer/oviewer.go
- oviewer/reader.go
Watch mode will reload at specified intervals.
Added an option flag to specify the Watch mode interval.
Added a flag to the document to prevent reloading.
> Added watch mode

- main.go
- oviewer/action.go
- oviewer/doclist.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/help.go
- oviewer/keybind.go
- oviewer/oviewer.go
- oviewer/reader.go
Stream mode resets and reloads if there is a blank line,
instead of watch mode.
This can be used for \watch in psql.
\setenv PSQL_WATCH_PAGER 'ov --stream'
> Added stream mode

- main.go
- oviewer/action.go
- oviewer/benchmark_test.go
- oviewer/document.go
- oviewer/event.go
- oviewer/oviewer.go
- oviewer/reader.go
Follow-mode needs to exit successfully for reload.
> Added context to cancel follow-mode

- go.mod
- go.sum
- oviewer/draw.go
- oviewer/move.go
- oviewer/oviewer.go
Divided and organized functions.
> Draw refactoring

- oviewer/action.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/move.go
Fixed incorrect nth specification in line.
> Move refactoring

- oviewer/event.go
It had to call the switch document.
> Fixed changing currentDoc directly

- oviewer/action.go
Fixed columnMode position not being set in wrapmode toggle.
> Fixed columnMode position

- example/exec/main.go
- oviewer/exec.go
Fixed the channel receipt omission of standard error output.
Added exec example.
> Fixed the channel receipt omission

- oviewer/action.go
- oviewer/document.go
- oviewer/oviewer.go
- oviewer/reader.go
Stop putting formfeed instead of EOF.
Add formfeed when reloading watch.
> Specification change of how to insert formfeed

- oviewer/action.go
- oviewer/event.go
- oviewer/move.go
Separate tailSection from follow().
moved the set of lastSectionPosNum.
> Clarification of the role of the lastSection move

- config_test.go
- ov-less.yaml
- ov.yaml
Removed duplicates in yaml settings.
> Added unmarshal to the test

- oviewer/draw.go
- oviewer/move.go
Change leftMostX to not return an error for non-existing rows.
> Allow moving above 0 rows

- oviewer/move.go
Fixed not to display minus line when pageup.
> Added limit to pageup.

- .github/workflows/build.yml
- .github/workflows/release.yml
- go.mod
- go.sum
Upgraded setup-go and changed the policy to use 'stable'.
> Changed policy to use 'stable'

- oviewer/action.go
- oviewer/document.go
- oviewer/oviewer.go
Multicolor setting by command line option applies to all documents.
> Moved multicolor settings from viewer to document

- oviewer/doclist.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/input.go
- oviewer/input_ba.go
- oviewer/input_delimiter.go
- oviewer/input_goto.go
- oviewer/input_header.go
- oviewer/input_jumptarget.go
- oviewer/input_multicolor.go
- oviewer/input_normal.go
- oviewer/input_search.go
- oviewer/input_section_delimiter.go
- oviewer/input_section_start.go
- oviewer/input_skip.go
- oviewer/input_tabwidth.go
- oviewer/input_viewmode.go
- oviewer/input_watch.go
- oviewer/mouse.go
Improved double set of InputMode.
Made the receiver name of the input event the same.
> Improved names for input events

- go.mod
- go.sum
- main.go
- oviewer/action.go
- oviewer/config.go
- oviewer/draw.go
- oviewer/keybind.go
- oviewer/oviewer.go
Added column rainbow mode that colors each column. Added viewMode option.
Resolve #236.
> Added column rainbow mode

- oviewer/content.go
- oviewer/event.go
- oviewer/input.go
- oviewer/input_delimiter.go
- oviewer/input_goto.go
- oviewer/input_header.go
- oviewer/input_jumptarget.go
- oviewer/input_multicolor.go
- oviewer/input_search.go
- oviewer/input_section_delimiter.go
- oviewer/input_section_start.go
- oviewer/input_skip.go
- oviewer/input_tabwidth.go
- oviewer/input_viewmode.go
- oviewer/input_watch.go
- oviewer/input_writeba.go
- oviewer/search.go
Changed order by fieldalignment to improve memory and performance.
> Change order by fieldalignment

- oviewer/action.go
Fixed that setting MultiColorWords in view-mode did not work.
> Fixed that setting MultiColorWords in view-mode

- README.md
This change makes the bullets look more alike (length, format).
> README: Rephrase intro bullets

- README.md
Depends on https://github.com/NixOS/nixpkgs/pull/209034 landing first.
> Add the nix install section

- README.md
- oviewer/help.go
Updated keybind and help in README.
Swapped the order of package installation.
> Missing help updates

- oviewer/move.go
- oviewer/utils.go
- oviewer/utils_test.go
Fixed a bug that didn't exit when substr was an empty string.
> Fixed a bug where allIndex never finished

- oviewer/document.go
- oviewer/document_test.go
- oviewer/draw.go
Styles are not applied after EOF.
Line numbers are not displayed after EOF.
> Do not apply styles to eof

- oviewer/content.go
- oviewer/oviewer.go
Added support for individual release of ANSI escape sequences. Supported individual release of 22-29.
> Added support for individual release of ES

- oviewer/content.go
- oviewer/content_test.go
Supports hyperlink escape sequences.
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda Refactored contents to allow adding osc.
> Added support for osc-8 hyperlinks

- README.md
Added example using regular expression for column-delimiter.
> Added example using regular expression

- README.md
- go.mod
- go.sum
Changed and unified the writing style of the default key. Add write-on-exit.
> Updated README.md feature description

- go.mod
- go.sum
- oviewer/reader.go
Fixed incorrect line count for long lines.
> Fix chunkPack for long lines

- go.mod
- go.sum
- main.go
- oviewer/action.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/exec.go
- oviewer/keybind.go
- oviewer/move.go
- oviewer/oviewer.go
- oviewer/reader.go
Added --column-width option.
Guess the column width, using https://github.com/noborus/guesswidth.
> Added column-width

- oviewer/document.go
> Fixed a mistake in specifying the number of lines

- oviewer/input.go
- oviewer/search.go
Fixed an issue where the last incremental search was running without being canceled.
> Fixed search cancel

- go.mod
- go.sum
- oviewer/document.go
- oviewer/exec.go
- oviewer/mouse.go
- oviewer/oviewer.go
- oviewer/reader.go
- oviewer/search.go
- oviewer/search_test.go
Improved so that errors can be wrapped and identified.
Added test for searchChunk.
> Improved by wrapping error

- go.sum
- oviewer/benchmark_test.go
- oviewer/document_test.go
- oviewer/event.go
- oviewer/oviewer.go
- oviewer/reader.go
- oviewer/reader_test.go
- oviewer/search_test.go
- oviewer/uncompress.go
- oviewer/utils_test.go
Added debug to output number of chunks being loaded.
> Improved comments

- main.go
- oviewer/config.go
- oviewer/control.go
- oviewer/oviewer.go
Fixed misconfiguration of variable to disable load-limit.
> Fixed variable to disable load-limit

- oviewer/control.go
- oviewer/document.go
- oviewer/event_test.go
- oviewer/exec.go
- oviewer/oviewer.go
- oviewer/search.go
Corrected output over ChunkSize in exec mode.
> Fixed chunks in exec mode

- oviewer/control.go
- oviewer/oviewer.go
- oviewer/reader.go
Fixed to be able to unload memory even in exec mode. Refactored into a function.
> Fix unload in exec mode

- oviewer/control.go
- oviewer/document.go
- oviewer/reader.go
Separated the conditions for reopen and seek in order to change the behavior depending on the file type.
> Separating reopen conditions and seek conditions

- oviewer/reader.go
Since it only counts and gets the size, it was improved to speed up.
> Improved newline counting

- oviewer/control.go
- oviewer/document.go
- oviewer/exec.go
- oviewer/help.go
- oviewer/logdoc.go
- oviewer/reader.go
- oviewer/search.go
Add lock because it gets caught in race conditions.
> Fixed race conditions

- oviewer/reader.go
> Fixed stdin for windows

- oviewer/chunk.go
- oviewer/control.go
- oviewer/oviewer.go
- oviewer/reader.go
- oviewer/search.go
Improved chunk management.
Centralize adding and removing chunks.
> Added chunk.go by refactoring

- oviewer/search.go
- oviewer/search_test.go
Enabled the m flag to match the end of a regular expression.
> Enabled the m flag for regular expressions

- oviewer/document.go
- oviewer/help.go
- oviewer/logdoc.go
- oviewer/reader.go
Supported EOF files without newline code code at the last line.
> Supported EOF without newline code code

- oviewer/reader.go
Already loaded loadChunk was not prevented.
> Fixed EOF processing without newline

- go.mod
- go.sum
- oviewer/control.go
- oviewer/reader.go
Loaded check was only for file.
> Fixed load not file

- README.md
- main.go
- oviewer/chunk.go
- oviewer/config.go
- oviewer/control.go
- oviewer/oviewer.go
- oviewer/reader.go
Improved so that memory-limit can be specified overall.
> Renamed load-limit to memory-limit

- oviewer/reader.go
Fixed a bug that chunks added when following were not used.
> Fixed adding to the previous Chunk when following

- oviewer/reader.go
Fixed the problem that the number of lines was shifted due to the timing of added lines.
Separate functions for filling chunks
and adding lines to avoid confusion.
> Fixed that the number of lines was shifted by addition.

- oviewer/chunk.go
- oviewer/control.go
- oviewer/document.go
- oviewer/exec.go
- oviewer/help.go
- oviewer/logdoc.go
- oviewer/move.go
- oviewer/oviewer.go
- oviewer/reader.go
- oviewer/search.go
- oviewer/store.go
Changed only the affiliation without changing the logic.
> Reduce document dependency by migrating from document to store

- oviewer/control.go
If the screen is displayed first, there is a problem with sudo, etc., so it was changed to wait until the first read.
> Changed to wait until the first read

- oviewer/control.go
- oviewer/document.go
- oviewer/logdoc.go
- oviewer/move.go
- oviewer/reader.go
- oviewer/search.go
- oviewer/store.go
- oviewer/store_test.go
> Changed startNum and endNum to atomic

- README.md
Fixed some typos.
Added in-page links.
> Added a command that can be used instead

- oviewer/action.go
- oviewer/draw.go
- oviewer/move.go
- oviewer/oviewer.go
- oviewer/search.go
fixed #368
Also fixed a missing cursor when toggling column mode.
> Improved horizontal scrolling

- oviewer/move_vertical.go
- oviewer/move_vertical_test.go
Set margin to 1 line (screen height - status line) -1.
> Add last line margin

- oviewer/action.go
- oviewer/move.go
- oviewer/move_vertical.go
- oviewer/move_vertical_test.go
> Unified to moveY

- oviewer/action.go
Fixed freeze issue when switching follow mode.
> revert acff59df

- oviewer/action.go
- oviewer/event.go
- oviewer/move.go
- oviewer/search.go
Move if the search term goes off screen.
If it nowrap mode, the x position will move.
If in wrap mode, move to the wrapping line where the search term is.
> Move if search term goes off screen

- oviewer/move.go
- oviewer/move_vertical.go
- oviewer/move_vertical_test.go
searchGo will definitely go to the target line
by allowing negative values.
> searchGo does not limit top

- oviewer/action.go
- oviewer/move.go
- oviewer/move_lateral.go
- oviewer/move_lateral_test.go
- testdata/ps.txt
Movement to the left and right only moved 1 even
if the amount was specified.
Reversed cycle specification.
If DisableCycle=true then cycle=false.
Added test.
> Fixed the amount of left/right movement

- README.md
- main.go
- oviewer/action.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/move.go
- oviewer/oviewer.go
- oviewer/search.go
Improved description of command line options.
> Change JumpTarget config name

- oviewer/config.go
- oviewer/control_test.go
- oviewer/input_multicolor.go
- oviewer/input_search.go
- oviewer/move_lateral.go
The search history is made a candidate so that it can be highlighted
in multicolor.
> Make search history a multicolor candidate

- oviewer/document.go
- oviewer/store.go
Export now keeps currentChunk unchanged.
GetLine is obsolete.
> Export changed getting line

- main.go
- oviewer/oviewer.go
- oviewer/reader.go
Added option to skip extraction of compressed files.
> Added option to `--skip-extract`

- main.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/input_savebuffer.go
- oviewer/move.go
- oviewer/move_vertical.go
- oviewer/oviewer.go
- oviewer/search.go
Fixed display of the line specified by section-delimiter. 
This lets users know which section they are scrolling through.
> Added section-header

- oviewer/draw.go
> Add sectionHeader to topLN

- README.md
- main.go
Made the explanation of skip-extract easier to understand. Added to README.md option description.
> Changed help description

- oviewer/input.go
- oviewer/input_delimiter.go
- oviewer/input_goto.go
- oviewer/input_jumptarget.go
- oviewer/input_multicolor.go
- oviewer/input_search.go
- oviewer/input_section_delimiter.go
- oviewer/input_section_start.go
- oviewer/input_tabwidth.go
- oviewer/input_watch.go
- oviewer/input_writeba.go
Stopped directly accessing the Candidate structure.
> Changed via method

- oviewer/oviewer.go
Adjust start when using section-header when writeOriginal.
> Adjust start when using section-header

- oviewer/config.go
- oviewer/event.go
- oviewer/oviewer.go
Added setting to stop displaying progress of line count.
> Added setting for the number of lines in progress

- oviewer/draw.go
There was an error in checking the number of columns.
> Fix when there are not enough columns

- oviewer/input_multicolor.go
- oviewer/input_search.go
- oviewer/input_search_test.go
- oviewer/input_test.go
Added test for candidate list.
searchCandidates has been changed to an input method.
> Added search input history test

- README.md
- ov.yaml
- oviewer/action.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/input.go
- oviewer/input_section_num.go
- oviewer/input_viewmode.go
- oviewer/keybind.go
Added section-header-num to help-key and help options. 
README.md has also been updated, as it has been added to the help. 
Improved comments.
> Added input mode for section header number

- oviewer/move_vertical.go
​
Fixed the number of lines to move when displaying minus lines.
> Fixed movement when displaying above line 0

- oviewer/draw.go
Fixed special treatment to start 0 only.
> Fixed cursor width in column mode

- .goreleaser.yml
This will also add 386.deb.
Solve #490
> Add 386-linux

- .github/workflows/build.yml
- .github/workflows/release.yml
- go.mod
- go.sum
Windows wide character issue resolved with tcell 2.7.1. (https://github.com/gdamore/tcell/releases/tag/v2.7.1)
> Updated modules

- main.go
- oviewer/document_test.go
- oviewer/filter.go
- oviewer/search.go
This is a feature that rechecks the file after reaching the last line. When the last line is updated when pipe or following, search will be performed again.
> Add recheck after reaching the last line

- oviewer/filter.go
- oviewer/render.go
recheck will revert because close processing fails.
> revert recheck

- oviewer/exec.go
The wait for exec is now done in the goroutine,
so it does not wait when there is a signal.
> Review exec wait processing

- oviewer/action.go
- oviewer/filter.go
- oviewer/move_vertical.go
- oviewer/render.go
Fixe the timing of inheriting the parent's Config.
> Fix option inheritance

- ov.plugin.zsh
easy install:
```
zinit load 'https://github.com/noborus/ov/blob/master/ov.plugin.zsh'
```
> feat: zsh completion plugin

- oviewer/action.go
- oviewer/doclist.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/filter.go
- oviewer/help.go
- oviewer/keybind.go
- oviewer/logdoc.go
- oviewer/oviewer.go
- oviewer/store.go
Add filter to close all documents.
Add documentType representing the document type,
and abolish screenMode.
Lock-free display of status messages.
> Add filter close all documents

- main.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/filter.go
- oviewer/input.go
- oviewer/input_search.go
- oviewer/keybind.go
- oviewer/move.go
- oviewer/search.go
Add non-match search feature to search for lines
that do not match the search string.
Add non-match-filter command line option.
> Add support non-match search

- oviewer/content.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/input_delimiter.go
- oviewer/input_filter.go
- oviewer/input_goto.go
- oviewer/input_header.go
- oviewer/input_jumptarget.go
- oviewer/input_multicolor.go
- oviewer/input_normal.go
- oviewer/input_savebuffer.go
- oviewer/input_search.go
- oviewer/input_section_delimiter.go
- oviewer/input_section_num.go
- oviewer/input_section_start.go
- oviewer/input_skip.go
- oviewer/input_tabwidth.go
- oviewer/input_viewmode.go
- oviewer/input_watch.go
- oviewer/input_writeba.go
- oviewer/reader.go
- oviewer/search.go
- **Refactor to use consistent parserState receiver**
- **Clean unused receivers**
> receiver cleanup

- oviewer/search.go
- oviewer/search_test.go
searchPositionStr is not exported and not used, it can be removed.
> Remove unused method

- oviewer/filter.go
- oviewer/render.go
It is better to include writer in filter.
> Stop including writer in render

- main.go
- oviewer/action.go
- oviewer/oviewer.go
General group allows setting of view mode.
> Transfer caption to general

- oviewer/input_search.go
- oviewer/move_vertical.go
> Add a comment about timeout

- oviewer/draw.go
- oviewer/input.go
- oviewer/input_search.go
- oviewer/input_search_test.go
- oviewer/oviewer.go
Change the search option to be set in advance.
> Improve the search prompt

- README.md
- main.go
- ov-less.yaml
- ov.yaml
Add QuitSmall section to README.md.
Add comments to the configuration template as well.
Sort by similar options.
resolve #544 .
> Add QuitSmall description

- oviewer/action.go
- oviewer/draw.go
- oviewer/move_lateral.go
- oviewer/move_vertical.go
- oviewer/reader.go
- oviewer/search.go
- oviewer/search_move.go
Improve by pointing out with lint.
Improvements to reduce usage of fmt.Sprintf.
> Improve code quality by fixing linting comments

- oviewer/draw.go
Fix the issue where the follow status was not displayed.
> Fix the issue where the status was not displayed

- oviewer/draw.go
- oviewer/move_vertical.go
Fixed SectionStartPosition movement.
Fixed hideoOtherSection conditions.
> Fixed section-start-position and hideoOtherSection

- oviewer/action.go
- oviewer/action_test.go
- oviewer/draw.go
- oviewer/draw_test.go
- oviewer/oviewer_test.go
- oviewer/prepare_draw.go
> Add a test for draw

- oviewer/action.go
- oviewer/draw.go
- oviewer/draw_test.go
- oviewer/exec_test.go
- oviewer/filter.go
- oviewer/filter_test.go
- oviewer/oviewer.go
- oviewer/oviewer_test.go
- oviewer/status_line_test.go
Change writeOriginal to support header and section headers. 
Improve coverage by running tests.
> Improve writeOriginal

- oviewer/action_test.go
- oviewer/doclist.go
- oviewer/filter_test.go
- oviewer/help.go
* Changed line number movement from event to direct.
* Added filter line number link test.
> Fixed moving to previous document

- oviewer/action.go
- oviewer/action_test.go
- oviewer/doclist_test.go
- oviewer/event.go
- oviewer/event_test.go
* Refactor tests for action.go and event.go
* Add tests for doclist.go
* Add tests for event.go
* Add tests for action.go
> Adding tests and refactoring for tests

- oviewer/action.go
- oviewer/action_test.go
- oviewer/draw.go
- oviewer/move_vertical_test.go
- oviewer/oviewer.go
- oviewer/prepare_draw.go
- oviewer/prepare_draw_test.go
- oviewer/save.go
- oviewer/save_test.go
* Since contents was used as a slice of content, rename map of line to lines.
* Add many action.go tests.
* Add save_test.go.
> Rename the map that stores lines to lines

- main.go
- oviewer/help.go
- oviewer/keybind.go
- oviewer/keybind_test.go
Add headings to make the help look good when organized into a table.
> Add a heading to the help

- oviewer/action.go
- oviewer/action_test.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/keybind.go
- oviewer/oviewer.go
- oviewer/oviewer_test.go
- oviewer/prepare_draw.go
- oviewer/search.go
- oviewer/search_move.go
- oviewer/search_test.go
* Add a test for search.
* Renamed "lastSearchNum" to "lastSearchLN" because it stores the line number.
> Add a test for search

- README.md
- main.go
Updated help and help-key to include other-hide-section.
> Update help & help-key

- oviewer/action_test.go
- oviewer/prepare_draw.go
- oviewer/prepare_draw_test.go
Changed findBounds to findColumnEnd.
Added a test for findColumnEnd.
Modified to reduce branching and simplify.
> Refactored columnwidth

- oviewer/action.go
- oviewer/action_test.go
- oviewer/doclist_test.go
- oviewer/oviewer_test.go
Change the number of output lines when WriteQuit
by specifying hide-other-section.
Added test for WriteQuit.
Minor test fixes.
> Change the number of output lines when WriteQuit

- oviewer/action.go
- oviewer/action_test.go
- oviewer/mouse.go
- oviewer/mouse_test.go
- oviewer/move_lateral.go
- oviewer/move_lateral_test.go
- oviewer/move_test.go
- oviewer/store.go
Stopped using getLineC and changed to get it from SCR.
Mouse selection is obtained from SCR information.
> Changed to use SCR

- oviewer/document.go
- oviewer/filter_test.go
- oviewer/prepare_draw.go
- oviewer/prepare_draw_test.go
Add a test for sectionTimeOut.
Fix test helper names.
Fix comments.
> Add a test for sectionTimeOut

- main.go
- oviewer/event.go
- oviewer/oviewer.go
- oviewer/oviewer_test.go
Separate run from prepareRun to make it testable.
Changed main.go to set only the QuitSmallFilter flag.
> Separate run from prepareRun

- oviewer/input.go
- oviewer/input_header.go
- oviewer/input_section_num.go
- oviewer/input_skip.go
- oviewer/input_test.go
Incrementing and decrementing numbers is redundant, so we will convert this into a function.
> Eliminate duplication of up and down

- main.go
- oviewer/convert_align.go
- oviewer/convert_raw.go
- oviewer/document.go
- oviewer/input_converter.go
- oviewer/oviewer.go
- oviewer/prepare_draw.go
- oviewer/prepare_draw_test.go
If the tab is separated using Align Converter, set the tab to 1. MaxwidthSdelm and Maxwidthswidth are normal functional and tested.
> Add a refactorig and test of Align Converter

- oviewer/convert_align.go
- oviewer/convert_align_test.go
Add a column check outside the array range.
Added a test with irregular columns.
> Fix crashing in an irregular column

- oviewer/action.go
- oviewer/action_test.go
- oviewer/keybind.go
Add a shortcut key that can easily select Align and Raw converters.
> Add a shortcut key that can easily select a converter

- ov-less.yaml
- ov.yaml
- oviewer/content.go
- oviewer/convert_align.go
- oviewer/oviewer.go
The "shrink" character can be changed in the settings.
For example, ShrinkChar: '>'
> Can change the character of "shrink" 

- oviewer/draw.go
- oviewer/prepare_draw.go
Change the function name that has the role of applying style.
> Change the style-related function name

- .goreleaser.yml
Change package name including version to goreleaser standard.
Fix #636.
> Fix the issue where the version contains "-1"

- main.go
Changes the default to not display the screen when redirecting. 
Requires the `--force-screen` option to display the screen.
This is a fix for #634.
> Change to Do not display screen when redirecting

- oviewer/action.go
Change to a terminal if the STDIN is not a terminal when using Subshell.
> STDIN switching when using Subshell

- oviewer/action.go
The doc.statusPos may not be updated.
> Re-fix the doc.height set

- oviewer/content_test.go
- oviewer/convert_es.go
- oviewer/convert_es_test.go
Replaced custom 8-bit color to RGB conversion with tcell.PaletteColor.
> Change to use tcell.PaletteColor

- oviewer/content.go
- oviewer/draw.go
- oviewer/oviewer.go
Summarize the definition of Content.
Unification of content variable names.
> Shrink content and improve rendering performance

- oviewer/control.go
- oviewer/document_test.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/example_test.go
- oviewer/move_vertical.go
- oviewer/reader.go
- oviewer/reader_test.go
Fixed the first position issue in Follow and Followall features.
Fixed an issue that Load was not in time by switching from tmpFollow. This could be a slightly off the position.
> Fix the first position of Follow and Followall

- oviewer/content.go
Fix Panic with irregular character bsContent.
> Enhance the length check of Contents

- oviewer/move_vertical.go
Add conditions to requestLoadSync to prevent display delay when reaching EOF.
> Add conditions for requestLoadSync

- oviewer/utils.go
Removed the custom implementations of max and min functions and used the standard library functions instead.
> Replaced custom max and min functions with standard library functions

- main.go
- oviewer/draw.go
- oviewer/event.go
- oviewer/oviewer.go
Added a feature to notify when EOF is reached by specifying the notify-eof option. 
Notifications are provided via screen display and beep sound.
> Add EOF notification feature

- README.md
Add the notify-eof option.
Add explanation for UnderlineStyle.
Add a note to quit if the content fits on one screen.
> Updated README.md by adding notify-eof option

- oviewer/prepare_draw.go
Added a check to findColumnEnd because the end may be smaller than the start.
> Add check range

- oviewer/draw.go
- oviewer/draw_test.go
- oviewer/move_lateral.go
- oviewer/prepare_draw.go
- Refactored function and variable names for better readability and maintainability.
- Added support for fullwidth characters to ensure proper display and handling.
> Refactor add support for fullwidth Characters

- oviewer/convert_align.go
- oviewer/convert_align_test.go
- oviewer/move_vertical.go
- oviewer/move_vertical_test.go
- oviewer/prepare_draw.go
- oviewer/prepare_draw_test.go
Corrected the logic to properly set the width of the last column.
> Fix setting the width of the last column

- oviewer/action.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/move_leftright.go
- oviewer/prepare_draw.go
ColumnStart is set to 1 if the column begins with the delimiter. headerColumn is calculated as headerColumn + columnStart.
> Changed to save columnStart and use it

- main.go
- oviewer/action.go
- oviewer/config.go
- oviewer/draw.go
- oviewer/keybind.go
- oviewer/move.go
- oviewer/oviewer.go
- oviewer/prepare_draw.go
- Added two types of rulers: absolute screen ruler and scroll-synchronized ruler.
- Toggle functionality to switch between the two rulers.
> Add ruler feature

- oviewer/move_leftright.go
- Corrected the logic in `optimalX` to ensure `x` does not become negative.
> Fix optimalX to prevent x from being negative

- README.md
- Added new features and updates for the upcoming v0.39.0 release.
- Significantly revised the features section to reflect the latest changes.
> Update README.md for v0.39.0 release

- README.md
- main.go
- oviewer/help.go
- oviewer/keybind.go
Added feature to detect duplicate keybinds.
Displayed with help-key option and help.
Updated section header to "Section operation".
> Added feature to detect duplicate keybinds

- oviewer/input.go
- oviewer/input_converter.go
- oviewer/input_delimiter.go
- oviewer/input_goto.go
- oviewer/input_header_column.go
- oviewer/input_jumptarget.go
- oviewer/input_multicolor.go
- oviewer/input_savebuffer.go
- oviewer/input_search.go
- oviewer/input_search_test.go
- oviewer/input_section_delimiter.go
- oviewer/input_section_start.go
- oviewer/input_tabwidth.go
- oviewer/input_test.go
- oviewer/input_vertical_header.go
- oviewer/input_viewmode.go
- oviewer/input_watch.go
- oviewer/input_writeba.go
- oviewer/oviewer.go
- oviewer/oviewer_test.go
Candidate list is now held in a map.
Added a function to check for exclamation marks.
> Changed to hold the list of candidates using a map

- main.go
> Add -m as a short option for --view-mode

- README.md
- ov-less.yaml
- ov.yaml
In the next release, v0.40.0, the style writing method will change.
ClipboardMethod will also be added.
> Updated for next release v0.40.0

- oviewer/oviewer.go
- oviewer/oviewer_test.go
Fixed incorrect movement of Caption variables due to setting changes.
> Fixed incorrect Caption variables

- oviewer/event.go
- oviewer/filter.go
Addresses style application issue when using both
--filter and --quit-if-one-screen options.
Styles are now correctly applied.
> fix: apply styles with --filter and --quit-if-one-screen

- ov-less.yaml
- ov.yaml
- Updated field names in `ov-less.yaml` and `ov.yaml` for consistency.
- Adjusted indentation in the configuration files for better readability.
> Fix sample config: update field names and adjust indentation

- oviewer/content.go
- oviewer/convert_align.go
- oviewer/doclist.go
- oviewer/doclist_test.go
- oviewer/draw.go
- oviewer/draw_test.go
- oviewer/filter.go
- oviewer/keybind.go
- oviewer/logdoc_test.go
- oviewer/mouse.go
- oviewer/mouse_test.go
- oviewer/move_leftright.go
- oviewer/move_updown_test.go
- oviewer/oviewer.go
- oviewer/prepare_draw.go
- oviewer/reader_test.go
- oviewer/status_line.go
- oviewer/store.go
- oviewer/store_test.go
- oviewer/utils.go
- oviewer/utils_test.go
- Updated multiple files to improve code readability and maintainability.
- Enhanced test coverage and updated test files for consistency.
- Minor updates to configuration and utility functions.
> Refactor codebase for modernization

- oviewer/prepare_draw.go
- Added missing bounds check to prevent out-of-range errors when handling slices.
> Fix missing slice bounds check

- oviewer/edit.go
Change default editor for Windows to Notepad.
Added error checking for os.Chmod.
> Change default editor for Windows only

- oviewer/edit.go
- oviewer/input.go
- oviewer/input_header.go
- oviewer/input_savebuffer.go
- oviewer/input_search.go
- oviewer/input_section_delimiter.go
- oviewer/mouse.go
- oviewer/save.go
- Fix incorrect comment describing eventHeader as "goto input mode"
- Improve function documentation for better code
> Improve comments and refactor code for clarity

- oviewer/mouse.go
- oviewer/oviewer.go
- Implement double-click detection with configurable interval and distance
- Add word boundary detection for smart text selection
- Enhance mouse event handling with click state management
- Support alphanumeric, whitespace, and symbol character types
- Improve user experience with intuitive text selection
> Add support for double-click word selection

- oviewer/action.go
- oviewer/config.go
- oviewer/document.go
- oviewer/draw.go
- oviewer/oviewer.go
- oviewer/oviewer_test.go
- Introduced PauseLine style to highlight the line where follow mode is paused.
- Updated draw logic to apply the new style when pauseFollow is active.
- Added pauseLastNum to track the paused line number.
- Updated Style struct and default style initialization.
> feat: Add style for paused line in follow mode
