noborus/ov

oviewer/draw.go

The calculation was wrong when the wide character came
to the end of the sentence.

Fixed position when the first line starts in the middle

---

oviewer/keybind.go

Because 'shift+A' comes when 'A' in the key event
of windows terminal.

For the'A'key, also enable'shift + A'

---

oviewer/content.go

`strings.Split` only returns an empty slice, if both arguments are empty [1], which is not the case here. So remove the check for empty slice, and also include empty string in check, to cover both these valid cases:
\x1b[0m
\x1b[m
1. https://golang.org/pkg/strings#Split

csToStyle: fix Normal logic

---

oviewer/mouse.go

Since even one character can be selected, x1 = x2 is correct.

Removed the check because it was unnecessary

---

go.mod
go.sum
oviewer/document.go
oviewer/oviewer.go

In wrap mode, calculate the lines to be displayed frequently
so that they are cached.

Cache wrapping calculation

---

oviewer/oviewer.go
oviewer/reader.go

Changed to strictly judge whether seek is possible
because a close error is output.

Avoid seek to check for close errors

---

ov-less.yaml

Improve #142.
Use `<` and `>` to move to the beginning and end.
Mark movement that has already been assigned is assigned with `alt+`.

Insufficient move key assignment for `less`

---

main.go
oviewer/content_test.go
oviewer/oviewer.go

OverStrikeStyle and OverLineStyle must be set before parse
to prevent race conditions.
setOldGlobalStyle is abolished
because it became difficult to set without collision.

abolished setOldGlobalStyle

---

main.go
ov.yaml
oviewer/action.go
oviewer/document.go
oviewer/document_test.go
oviewer/draw.go
oviewer/event.go
oviewer/input.go
oviewer/keybind.go
oviewer/logdoc.go
oviewer/move.go
oviewer/oviewer.go

Enables writeOriginal to be output by specifying the lines
before and after the current line.
Writing the settings in ~/.ov.yaml is similar to the behavior
of `less -X`.
BeforeWriteOriginal: 1000
Added cli options write-exit-before(b) and write-exit-after(a)
(cli option takes precedence).
If the value of write-exit-after is set to 0,
it will be the current screen height.
Added CurrentLN() to the document to return the number of current line.
Added Export() to output the specified line(range) from the document.
Fix #48.
A discussion of this fix was made in #146. Thank you @aranjan7.

Before and after also enable WriteOriginal

---

oviewer/action.go
oviewer/document.go
oviewer/draw.go
oviewer/oviewer.go
oviewer/oviewer_test.go

Sometimes screen.Clear() flickers on windows terminal.
Therefore, stop clearing the whole.
This may improve #144.
Fixed openFile not being aligned with others by refactoring.

Changed not to clear the whole

---

oviewer/oviewer.go
oviewer/reader.go

Because eofCh reception was insufficient at the time of New Root.
This commit fix #164

Fixed docSmall() not working for NewRoot

---

oviewer/draw.go

If the character with width 2 is at the right end,
the rightmost width 1 may be empty.

Fixed clear leak at the right end

---

oviewer/move.go

The bottom line calculation when using skip-lines was incorrect.

Fixed bottom line calculation

---

main.go

os.Stderr was displayed on the screen by exec and it was broken.

Fixed a misjudgment of redirect

---

README.md
ov-less.yaml
ov.yaml
oviewer/keybind.go
oviewer/move.go
oviewer/oviewer.go

Changed the default color of section lines.

Show message when next section is missing

---

main.go

Fixed to work when the config file doesn't exist

---

.github/workflows/release.yml
.goreleaser.yml

CI: Generate release tarballs with vendored modules

---

main.go
ov-disable-default.yaml
oviewer/action.go
oviewer/doc.go
oviewer/keybind.go
oviewer/oviewer.go

Set **DefaultKeyBind:** to "disable".
This setting requires keybindings to be set appropriately.
An example of a setting that only allows exit and
forward/backward movement.
```console
ov --config ov-disable-default.yaml README.md
```

Disable default keybindings

---

.github/workflows/release.yml
.goreleaser.yml

goreleaser can now create a tar with the vendor included. Abolished uploading that was done with github actions.

Updated goreleaser

---

go.mod
go.sum
main.go
oviewer/action.go
oviewer/document.go
oviewer/draw.go
oviewer/keybind.go
oviewer/oviewer.go

Plain mode disables the original escape sequences. Plain mode works with the `--plain` option
or toggle with the default (ctrl+e) key.

Added plain mode

---

go.mod
go.sum
main.go
oviewer/action.go
oviewer/draw.go
oviewer/event.go
oviewer/input.go
oviewer/keybind.go
oviewer/mouse.go
oviewer/oviewer.go
oviewer/search.go
oviewer/utils.go

Added a jump target that shifts the position of search results. Display the search results at the specified position instead of 0 lines.
Added `-j` `--jump-target` option.
Added input key (default j).
Added to be able to set the style (StyleJumpTargetLine) to the corresponding line of jump-taget.
Resolve #220.

Added jump target

---

ov.yaml
oviewer/help.go
oviewer/oviewer.go

Help headings are divided into sections
to make it easier to navigate and see.
Changed section style color.

Added section breaks to help

---

oviewer/document.go

Execute BuffEndNum() outside the loop for better performance.

Execute BuffEndNum() outside the loop

---

oviewer/input.go
oviewer/input_ba.go
oviewer/input_delimiter.go
oviewer/input_goto.go
oviewer/input_header.go
oviewer/input_jumptarget.go
oviewer/input_multicolor.go
oviewer/input_normal.go
oviewer/input_search.go
oviewer/input_section_delimiter.go
oviewer/input_section_start.go
oviewer/input_skip.go
oviewer/input_tabwidth.go
oviewer/input_viewmode.go
oviewer/input_watch.go

The file was split because the number of input modes increased.

Split input into files

---

ov-less.yaml

With this change ov-less.yaml makes ov act more like less.  `g` was one of the first things I tried.

Make `g` bring us to the top and use `:` to go to a specific line number

---

README.md
main.go
ov-less.yaml
ov.yaml

This PR implements the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for the configuration file.
If merged, ov will look for the configuration file in the following paths in descending order:
```filepath
$XDG_CONFIG_HOME/ov/config.yaml
$HOME/.config/ov/config.yaml
$HOME/.ov.yaml
```
The original home path is preserved for backwards compatibility, so that users who update the software will not be interrupted by a missing config problem.

Default to XDG configuration directory

---

oviewer/doclist.go
oviewer/document.go
oviewer/oviewer.go

Make it a function because regular expression compilation leaks.

Compile regular expressions for documentation

---

oviewer/move.go

There was a bug when specifying a non-existent delimiter in the file.

Fixed the logic that columnModeX should return 0

---

oviewer/action.go
oviewer/oviewer.go

Changed to overwrite with options after merging view-mode and config. For example,
`--view-mode csv` and `--follow-mode` can be used together.

Enable view-mode and option together

---

oviewer/move.go

top and bottom do not need to reset keys.
Prevents keys from being reset in `--follow` mode.

Stop resetting top and bottom keys

---

oviewer/action.go
oviewer/document.go
oviewer/draw.go
oviewer/input_delimiter.go
oviewer/move.go
oviewer/oviewer.go
oviewer/search.go
oviewer/search_test.go
oviewer/utils.go
oviewer/utils_test.go

A string enclosed by `/` and `/` in ColumnDelimiter is interpreted as a regular expression.
For example, write regular expressions like /[,|;]/ and /\s+/. If the condition is not met, it will be interpreted as a string.
Resolve #251

Enable regular expressions in ColumnDelimiter

---

oviewer/content.go
oviewer/content_test.go

BEL (\a) characters are used instead of \x1b\\ at the end of the URL.

Supports BEL (\a) characters

---

go.mod
go.sum
main.go
oviewer/action.go
oviewer/doclist.go
oviewer/document.go
oviewer/document_test.go
oviewer/draw.go
oviewer/event.go
oviewer/exec.go
oviewer/logdoc.go
oviewer/move.go
oviewer/oviewer.go
oviewer/reader.go
oviewer/reader_test.go
oviewer/uncompress.go

Stops storing all read files in memory.
This change applies to regular files only,
not pipes or compressed files.
Change to control by channel to make
it work more asynchronously.
Change File Watch to Directory Watch
to react to file descriptor changes.

Major changes in memory usage

---

oviewer/action.go
oviewer/draw.go
oviewer/reader.go

stdin cannot be reloaded if it has reached EOF.
Changed display of follow-name as it doesn't work
without follow-mode enabled.

Add reload condition

---

oviewer/mouse.go

The y coordinate was omitted in the condition
for exchanging x2 and x1.

Fixed the mouse select x position shifting

---

go.mod
go.sum
main.go
oviewer/action.go
oviewer/config.go
oviewer/control.go
oviewer/doclist.go
oviewer/document.go
oviewer/exec.go
oviewer/oviewer.go
oviewer/reader.go
oviewer/search.go

Seekable files behave differently than others.

Made it possible to set a memory limit

---

oviewer/reader.go

Fixed to lock and count only the last time.

Further speed improvement

---

oviewer/reader.go
oviewer/search.go

Changed to be able to search while reading the contents that have not been read yet when load-limit is specified. If the starting position has been evicted from memory, move the starting position.

Change search for non-seek files and load-limit

---

oviewer/reader.go

Fixed some EOF cases without newlines at Chunk boundaries. One line was missing when there was a line without a line break at the end of the chunk.

Fixed EOF on chunk boundaries

---

oviewer/help.go

Since requestLoad is required, help also requires ControlReader.

Fixed help search.

---

oviewer/control.go
oviewer/control_test.go
oviewer/doclist.go
oviewer/document.go
oviewer/draw.go
oviewer/exec.go
oviewer/help.go
oviewer/logdoc.go
oviewer/reader.go
oviewer/search.go
oviewer/store.go

If follow-mode is set and EOF is not reached,
set temporary follow-mode.
Temporary follow mode seeks to the end of the file before reading. Then return to normal read.

quickly move to tail

---

ov.yaml
oviewer/oviewer.go
oviewer/search.go
oviewer/search_test.go

Implement smartcase search

---

oviewer/action.go
oviewer/action_test.go
oviewer/config.go
oviewer/event.go
oviewer/move.go
oviewer/oviewer.go

Enabled to specify section as well as jump-target value and %.
If `--jump-target section` is specified, it will be displayed from the beginning of the section as much as possible.
The actual jump-target is shown variable.

Enabled to specify section for jump-target

---

oviewer/action.go
oviewer/control.go
oviewer/document.go
oviewer/event.go
oviewer/move.go
oviewer/reader.go

moveBottom immediately moves to the bottom line.
At the timing of switching from tmpRead,
the number of lines from the bottom line is inherited to the current number of lines.

Quickly move to bottom line

---

oviewer/control.go

Send requestEnd() only when not tmpFollow to reduce redundant requests.

reduce redundant requests

---

oviewer/move.go
oviewer/move_vertical.go

There was too much movement when moveYDown was in noWrapMode. 
Improved searchGoSection when using skip+header.

Fixed bug in moveYDown

---

oviewer/search.go

Unnecessary requestLoad was taking time
when receiving a long output by pipe.
Changed to reset the search character
when an empty character is specified in input_search.

RequestLoad only when necessary

---

oviewer/control.go
oviewer/control_test.go
oviewer/document.go
oviewer/move_vertical.go

Since loadrequest may be waiting for read, make it asynchronous.
Changed not to cache lines that are not in the buffer.

Make loadrequest asynchronous

---

oviewer/move.go

Avoid bottom line when jump-target is set to section.

Avoid bottom line when jump-target

---

README.md

Resolve #427
Added description of style specification for
StyleColumnRainbow and StyleMultiColorHighlight.

Added description of StyleColumnRainbow.

---

main.go

- `--pattern` option is used to search by pattern. Equivalent to less's `--pattern` option.
This implements #430.

Added option to search by `pattern` option

---

oviewer/action.go
oviewer/doclist.go
oviewer/document.go
oviewer/document_test.go
oviewer/event.go
oviewer/input.go
oviewer/input_savebuffer.go
oviewer/keybind.go
oviewer/oviewer.go
oviewer/save.go
oviewer/search.go

Add filename input to save buffer.
The buffer can be saved in anything other than a regular file.
Confirm whether to overwrite the file.
Change Export to return an error.
This solves #418.

Add save buffer

---

go.mod
go.sum

Fixed to register ctrl+h as backspace,
because there was a problem where ctrl+h was registered as ctrl+backspace.

Updated cbind module

---

go.mod
go.sum
main.go
oviewer/action.go
oviewer/action_test.go
oviewer/help.go
oviewer/keybind.go
oviewer/mouse.go
oviewer/move.go
oviewer/oviewer.go

Add horizontal scroll by specified amount 

---

oviewer/document.go
oviewer/draw.go
oviewer/move_vertical.go

Changed policy to adjust section header movement only when moving to the beginning.

Adjust position only when moving to the beginning

---

main_test.go
oviewer/keybind.go
oviewer/oviewer_test.go

Fixed the keybind action name to section_header_num. 
Added configuration yaml test.
Added test for names in config.

Fixed action name in config

---

README.md

This pull request add two other AUR flavours, `ov` and `ov-git`. If merged, it will close #470.

Add missing AUR flavours: ov and ov-git

---

main.go

Windows does not expand wildcards using the shell, so use filepath.Glob.

Enabled wildcard specification even on Windows

---

main.go

Fixed to return correct error if filePath.Glob does not match.

Fixed to return correct error

---

oviewer/draw.go
oviewer/move_vertical.go

Fixed an issue where the program would freeze
if a section header line was not found in a large file.
Set the search timeout to 1 second and reset the search string if it takes longer.

Added timeout processing for section header search

---

main.go

viper.Unmarshal should run even if the configuration file is missing.
This is a fix for #488.

Fix when configuration file is missing

---

oviewer/content.go
oviewer/content_test.go
oviewer/event.go
oviewer/mouse.go
oviewer/oviewer.go
oviewer/search.go

pos.n() was returning 0 when the value was over,
so it was corrected to the maximum width.
Replace OverLine with Underline,
as tcell does not support OverLine.

Added proactive fixes and tests

---

README.md

The fact this was missing could cause into a lot of problems and frustration while the information are already available on the website

Improve README by pointing out where the documentation is located

---

biomap/biomap.go
biomap/biomap_test.go
oviewer/action.go
oviewer/control.go
oviewer/doclist.go
oviewer/document.go
oviewer/draw.go
oviewer/event.go
oviewer/filter.go
oviewer/input.go
oviewer/input_search.go
oviewer/keybind.go
oviewer/logdoc.go
oviewer/logdoc_test.go
oviewer/oviewer.go
oviewer/render.go
oviewer/search.go

Add filter search feature to search documents by filter. The 'biomap' package, which provides a bidirectional map, is also added to support this feature.
The filter function filters only the lines containing word in the current document and creates a new document.
Link the line numbers of the new document
to the line numbers of the original document.
This implements #493.

Add filter search and related packages

---

main.go
oviewer/oviewer.go

Add option `--caption` to set caption.
Also add the environment variable `OV_CAPTION` to set the caption.
Since we put `viper.SetEnvPrefix("ov")`,
the environment variables must have the `OV_` prefix.
This implements #498 .

Add caption options and environment variables

---

oviewer/draw.go

Do not display if the display area is not secured
for line number display.

Fix crash issue with line number display

---

oviewer/keybind.go

On Windows, `!"#$%&` is also recognized by Shift+, so expand the scope.

Expand the scope from 'A'-'Z' to '!'-'`'

---

oviewer/benchmark_test.go

Test helpers should use t.Helper()
This way if an error occurs it would be reported outside the helper

Fix test helpers

---

oviewer/draw.go

It was necessary to manage the cursor position and string separately.

Fix incorrect cursor position

---

oviewer/draw.go
oviewer/move_vertical.go

The timeout settings were applied at the wrong locations.
Resolves the TODO.

Apply timeout settings at correct locations

---

oviewer/document.go
oviewer/exec.go
oviewer/move.go
oviewer/move_lateral.go
oviewer/move_vertical.go
oviewer/oviewer.go

Disable SectionHeader when in watch mode.
Because it outputs the wrong sectionHeader.

Refactor the section move

---

oviewer/document.go

Set to fileName instead of caption to enable
settings to suppress display.
fix #553

Set to fileName instead of caption

---

oviewer/action.go
oviewer/document.go
oviewer/draw.go
oviewer/move.go
oviewer/move_vertical.go
oviewer/oviewer.go
oviewer/search.go
oviewer/search_move.go

The displayed lines have been changed so that they are not affected by section headers.
However, if there are lines that should be displayed, they will be displayed by avoiding the section headers.
Also, if necessary, the search will start from the previous search line. Changed to display the mark style higher than the section-Header style.

Changed the method of implementing section-header

---

oviewer/draw.go

JumpTarget takes precedence over section header movement.

jumpTarget takes precedence

---

oviewer/action.go

Fix to print errors on suspend to stderr,
as SetContent would freeze on resume.

Fix to output errors during suspend to stderr

---

main.go
main_test.go

Fixed a misunderstanding about how viper detects errors. 
Related: https://github.com/spf13/viper/issues/1139
This is a re-fix of #488.

Ignore "config not found" errors if not specified

---

README.md

as i tried to check for the fix to the erroneous `failed to read config file` message (as shown in #488), i first executed `go install github.com/noborus/ov@latest`, which just fetched the latest release build and did not included the fix (i wasn't aware of how to install from the `master` branch at the time). when i followed the option of `go get -d github.com/noborus/ov`, i got an error from `go` itself, saying:
```console
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
i assume that those …

docs: 📝 update instructions for source installation

---

oviewer/oviewer.go
oviewer/oviewer_test.go

So that you don't have to call preparaDraw
before calling writeOriginal.
This is because docSmall is called before preparaDraw.

Call preparaDraw in writeOriginal

---

oviewer/filter.go
oviewer/filter_test.go

filter was not copying headers correctly when skip-lines was specified. It copies both skip-lines and headers.

Fixed filter when skip-lines is specified

---

main.go
oviewer/event.go
oviewer/oviewer.go
oviewer/oviewer_test.go

Changed when using --quit-if-one-screen and --filter together. 
Quit when the filter result fits within the screen.
Delay the determination that it fits within the screen.

Quit when the filter result fits within the screen

---

oviewer/action_test.go
oviewer/document.go
oviewer/move_lateral_test.go
oviewer/prepare_draw.go
oviewer/prepare_draw_test.go

This reverts commit  6f70679ed95b2edc06e0385ec5af6c48873bccd0. The scr was insufficient to determine the width.
Also, if the file is not fully loaded, it will not be determined.

Revert 6f70679

---

README.md

Added the case where both filter and quit one screen are specified.

Added filter and quit one screen options

---

oviewer/input.go
oviewer/input_search.go
oviewer/input_search_test.go

Fixed a bug where exclamation marks could not be entered (with the default key bindings).
Normal input is now possible outside of filter.
In filter, they can be entered by placing a backslash in front of them.

Fixed exclamation mark input

---

go.mod
go.sum
oviewer/content.go
oviewer/convert_align.go
oviewer/convert_es.go
oviewer/document.go
oviewer/move_vertical.go
oviewer/prepare_draw.go
oviewer/utils.go
oviewer/utils_test.go

Add converter align to align columns split by dlimiter and columns split by width.
Adds space to columns that are short of space to fit the maximum width of columns on the screen.
Add support for disabling delimiters in double quotes.

Add align converter 

---

oviewer/search.go

Fix the conditions of incremental search,
If the event is accumulated, do not execute.
The paste on the system side (not a `tcell` event) is to miss the event because a key event occurs for each character.
This fixes #613.

Fix paste mistakes

---

oviewer/action.go
oviewer/action_test.go
oviewer/draw.go

Avoid the section header and mark it, when marking.
This solves #620.

Avoid sector header when marking

---

oviewer/action.go
oviewer/action_test.go
oviewer/convert_align.go
oviewer/convert_align_test.go
oviewer/document.go
oviewer/input_converter.go
oviewer/input_viewmode.go
oviewer/keybind.go
oviewer/oviewer.go
oviewer/oviewer_test.go
oviewer/prepare_draw.go
oviewer/prepare_draw_test.go

Change the general name forward for variables.
Add ColumnAttribute and put shink and right align inside.
Added ShrinkColumn and ExpandColumn.

(Re -revision)Change the name of the variable name

---

main.go
oviewer/oviewer.go

Add a shortcut specified by RAW and Align converter.

Add a converter specified shortcut

---

oviewer/convert_align.go
oviewer/prepare_draw.go
oviewer/prepare_draw_test.go

Add the start position to the COLUMN judgment.
Make variable names easier to understand for refactoring. 
Add Comment.

Improve column's overflow

---

oviewer/action.go
oviewer/action_test.go
oviewer/convert_align.go
oviewer/convert_align_test.go
oviewer/document.go
oviewer/move_lateral.go
oviewer/move_lateral_test.go
oviewer/move_test.go
oviewer/prepare_draw.go
oviewer/prepare_draw_test.go

If it starts with the Delimiter character (enclosed by Delimiter), change the start of the line from 1 instead of 0.
Maxwidth is changed to the width excluding delimiter.
Add Column to add AppendColumn as a function.
Improve comments.

Change the specifications of column by delimiter

---

oviewer/action.go
oviewer/action_test.go
oviewer/suspend.go
oviewer/suspend_windows.go

Change suspend from subshell to SIGSTOP suspend.
However, if Windows or OV_SUBSHELL is set, it will remain in subshell.
Solve #630.

Change to suspend with SIGSTOP

---

main.go
oviewer/content.go
oviewer/convert_es_test.go
oviewer/input_search_test.go
oviewer/keybind.go
oviewer/mouse_test.go

- Improved command-line help and help descriptions for better clarity.
- Fixed typos in various files.

help descriptions for better clarity

---

oviewer/suspend.go

This change ensures that all processes in the group are suspended, not just the main process.
It was modified by the re-comment of #630.

Send SIGSTOP to the process group

---

oviewer/action.go
oviewer/action_test.go
oviewer/event.go
oviewer/search.go

Change searcher to an argument,
because root.searcher will be in a race condition in another goroutine.
This is a fix to #641.

Fixed root.searcher is race condition

---

oviewer/doclist.go

Fixes misalignment of line number linkage
when the filter document has a header.
Add nil check as a precaution.

Fix linkage of filter documents with headers

---

oviewer/action.go
oviewer/action_test.go
oviewer/event.go

Fix followAll for omission of doc.height update.
Reduce branching of follow* to make it clearer.

Improve follow/followAll/followSection

---

oviewer/content.go
oviewer/content_test.go
oviewer/convert_es.go
oviewer/document.go
oviewer/draw.go

ov(and other pagers) cannot be erased.
Actually, set the style from the end of the line.
This solves #650 .

Add support of ANSI escape sequence for clear line

---

oviewer/convert_es.go
oviewer/convert_es_test.go
oviewer/oviewer.go

- Enhanced handling of invalid values in escape sequences to better match terminal and `less`` behavior.
- Updated related functions to ensure compatibility.
- Improved error handling and reporting for invalid escape sequences.

Improve escape sequence compatibility

---

oviewer/convert_es.go
oviewer/convert_es_test.go
oviewer/oviewer.go

Separated SGR within CSI and supported colon-separated SGR. Also supported redundant SGR specifications.
The color specification of the SGR is invalidated outside the range, and the invalid string becomes an error.

Add support for colon-separated values

---

oviewer/content_test.go
oviewer/convert_es.go
oviewer/oviewer.go
oviewer/ovstyle.go

Add escape sequences that tcell does not support to OVStyle.
Separate ovstyle.go from oviewer.go.

OVStyle adds supported escape sequences

---

oviewer/content_test.go
oviewer/convert_es.go
oviewer/convert_es_test.go

The OSC hyperlink has also been rewritten to match CSI. Fixed so that the text does not disappear even
when an error occurs.

Reimplemented osc hyperlink

---

oviewer/convert_es.go
oviewer/convert_es_test.go

There was an incompatibility in handling invalid osc, so this has been re-fixed. oscStyle has been modified to take style as an argument.

Fixed incompatibility in handling invalid osc

---

oviewer/control_test.go
oviewer/document.go
oviewer/document_test.go
oviewer/filter_test.go
oviewer/oviewer_test.go
oviewer/reader.go

Added `WaitEOF` function to wait for EOF notification.

Add function to wait for EOF

---

oviewer/event.go
oviewer/event_test.go
oviewer/oviewer.go

Fix DocumentLen() out-of-range checks that were incorrect.

Fix DocumentLen() out-of-range checks

---

oviewer/move_vertical.go
oviewer/move_vertical_test.go

Modified the behavior to allow the last line to be scrolled to the top of the screen when wrap mode is disabled.

Allow scrolling the last line to the top

---

oviewer/action.go
oviewer/document.go
oviewer/move.go
oviewer/move_lateral.go
oviewer/move_lateral_test.go
oviewer/move_test.go
oviewer/oviewer.go
oviewer/prepare_draw.go
oviewer/prepare_draw_test.go

Refactor to use columnRanges and improve column cursor movement

Refactor to use columnRanges and improve column cursor movement

---

oviewer/move_lateral.go

Corrected the logic to ensure the x start position does not become negative when moving the cursor to the rightmost position.

Fix x start position to not be negative when moving to rightmost cursor

---

oviewer/action.go
oviewer/search.go
oviewer/search_move.go

Fixed the issue where the x position was adjustedif the search term was hidden. If the search term was at the edge, the end position of the search term now scrolls to the right edge.

Adjust x position if search term is hidden

---

main.go
oviewer/draw.go

- Fixed issue where StyleHeaderBorder was applied even when the header was not present.
- Improved the description of the ruler option in the documentation.

Fix StyleHeaderBorder and ruler

---

go.mod
go.sum
main.go
oviewer/action.go
oviewer/action_test.go
oviewer/config.go
oviewer/keybind.go
oviewer/oviewer.go
oviewer/search.go

This commit modifies the terminal output behavior of the pager. Previously, the terminal output was limited to the original text content. Now, it outputs the processed content displayed on the pager, including features like search highlights.
Key changes:
- Added functionality to toggle between outputting the original text and the processed screen content.
- Implemented a dummy screen rendering for cases where the content fits within the terminal, ensuring consistent processing.
- Changed the default behavior to output the processed screen content. Users can switch to the original text output via a toggle key or configuration.
Notes:
- Users who prefer the original text output must update their configuration.
- The output now uses ANSI escape sequences for styling. Terminals that do not …

feat: Add styled terminal output with toggleable raw text option

---

oviewer/config.go
oviewer/oviewer.go

Implemented a fix for issue #739 by adding a configurable minStartX to set the minimum starting position (x) for document display.
The default value is set to 0.

make minStartX configurable with default value 0

---

ov-less.yaml
ov.yaml
oviewer/action.go
oviewer/action_test.go
oviewer/config.go
oviewer/draw.go
oviewer/draw_test.go
oviewer/oviewer.go
oviewer/prepare_draw.go
oviewer/prepare_draw_test.go

Change Style config from Style* prefix to general/Style/.
This allows styles to be specified in Mode/Style as well.
The old Style* format is still supported but deprecated.
Updated `ov-less.yaml` and `ov.yaml` for improved style consistency.

Change Style config to general/Style/

---

oviewer/config.go
oviewer/mouse.go

Implemented clipboard functionality using OSC52 escape sequences.
This needs to be set to enable copying with OSC52.
This implements #747 .

Added clipboard via osc52

---

main.go

The change to IsWriteOnExit was not reflected in main.go.

Missing variable name changes

---

README.md

- Added details about the `ClipboardMethod` configuration.
- Explained how to use the `OSC52` escape sequence for clipboard operations.

Update Mouse support section in README.md

---

oviewer/oviewer.go

Fixed an issue where Style remained blank when config.yaml was missing. This occurred because old settings were applied even when Style was blank, leading to a blank configuration when config.yaml was absent.
With this fix, old style settings will not be applied if Style is blank.
fix #760

fix: #760 Do not apply old style settings when Style is blank

---

ov-less.yaml
ov.yaml
oviewer/config.go
oviewer/document.go
oviewer/filter.go
oviewer/oviewer.go
oviewer/search.go

Addressed an intermittent search failure when using `ov` with `man`. 
The initial search now waits for EOF or the configured `ReadWaitTime` before starting, ensuring proper handling of input streams. 
fixed #765

fix: Wait for EOF or ReadWaitTime before starting initial search

---

oviewer/oviewer.go

The WaitEOFWithTimeout call was causing a 1-second delay when opening large files, which was unnecessary for file size checking.

Remove WaitEOFWithTimeout call when checking file size

---

oviewer/content.go

Simplified conditional logic by replacing an `if` statement with a `switch` statement for better readability and maintainability.

Refactor: Replace if statement with switch statement

---

examples/search/main.go
main.go
oviewer/action.go
oviewer/action_test.go
oviewer/document.go
oviewer/draw.go
oviewer/oviewer.go
oviewer/oviewer_test.go
oviewer/prepare_draw_test.go

Stopped embedding Screen and Config in the struct. Updated Doc to handle RunTimeSettings without embedding, addressing the issue with "could remove embedded field 'RunTimeSettings' from selector".

Refactor: Adjust struct embedding for Screen, Config, and RunTimeSettings

---

README.md

Added a note that StyleOverStrike and StyleOverLine cannot be specified in view mode. 
Fixed #770.

Add note StyleOverLine and StyleOverStrike

---

oviewer/action_test.go
oviewer/convert_es_test.go
oviewer/prepare_draw_test.go

- Added `TestRoot_setViewMode` in `action_test.go` to test `setViewMode` behavior.
- Extended `Test_sgrStyle` in `convert_es_test.go` with new cases for underline styles and colors.
- Added a new case to `Test_findColumnEnd` in `prepare_draw_test.go` to test column end calculation.

Add tests to improve coverage

---

oviewer/convert_es.go
oviewer/convert_es_test.go
oviewer/ovstyle.go

Add support for handling the `ESC(B` sequence as a reset operation. This ensures compatibility with additional escape sequences and improves robustness in sequence handling.
fix: #774

Add support for `ESC(B` as a reset operation in other sequence handling

---

oviewer/action.go
oviewer/document.go
oviewer/edit.go
oviewer/store.go
oviewer/utils.go

When executing edit in plain mode, escape sequences are stripped before passing to the editor.

Enable passing stripped escape sequences to the editor

---

README.md
ov-less.yaml
ov.yaml
oviewer/config.go
oviewer/event.go
oviewer/oviewer.go
oviewer/status_line.go

Move prompt settings to general and add cursortype settings.
Add a note to README.md that the StatusLine can now be hidden.
Add StatusLine style settings.
The old prompt settings are still valid.
This is the remaining implementation of #426.

Move prompt settings to general and add other settings

---

oviewer/action.go

Fix the method for specifying documents that do not allow WriteQuit.
Add a filter document to allow WriteQuit.

Fix the method for specifying documents

---

go.mod
oviewer/suspend_other.go
oviewer/suspend_unix.go

- Rename suspend.go to suspend_unix.go for Unix-specific implementation
- Rename suspend_windows.go to suspend_other.go for other platforms
- Update go.mod dependencies
Fixes #805

Fix Getpgrp support for cross-platform compatibility

---

oviewer/suspend_solaris.go

Created suspend_solaris.go with proper error handling for unix.Getpgrp(). 
Updated suspend_unix.go build constraint to exclude solaris and illumos.
Fixes #805

Separate Solaris/Illumos suspend implementation

---

README.md

- Update Homebrew installation instructions to prioritize official formula
- Add note about alternative tap installation method
- Homebrew Core formula is now available as 'brew install ov'
Closes #450

Update README to reflect Homebrew Core availability

---

README.md

- Added TIP callouts for common use cases and best practices
- Included tips for regex delimiters, memory limits, follow modes, and configuration
- Enhanced user guidance for practical scenarios like SSH clipboard operations
- Improved documentation readability with actionable advice

Add helpful tips to README.md

---

oviewer/action.go
oviewer/mouse.go
oviewer/utils.go

When column selection is available, double-click now selects the column instead of a word. Refactored double-click handling to support both word and column selection. Updated selection logic and related functions to handle column boundaries. Reset selection when mouse actions cause selection to shift. Refactoring mouse variables.

Enable column selection on double-click

---

oviewer/doclist.go
oviewer/draw.go
oviewer/event.go
oviewer/move.go
oviewer/oviewer.go

Always start a goroutine to monitor EOF, regardless of notify-eof option. On EOF, check if docSmall should trigger auto-quit. This enables correct auto-quit even when file reading is slow or delayed. Fixes issue #853.

Monitor EOF with goroutine and check docSmall for auto-quit timing

---

oviewer/doclist.go

- Changed document list operations to use TryLock instead of Lock
- Log a message when lock acquisition fails, without UI update
- Prevents potential deadlocks and improves responsiveness

fix: Use TryLock for doclist operations and log lock failures

---

ov.yaml
oviewer/help.go
oviewer/keybind.go

- Add normalizeKey() and normalizeKeyWithPrefix() functions to handle key notation variations (e.g., "ctrl+c" vs "Ctrl+C")
- Update findDuplicateKeyBind() to return both duplicates and errors
- Improve error handling to collect all validation issues instead of stopping at first error
- Enhance DuplicateKeyBind() to display invalid key bindings with clear error messages
- Rename duplicate struct to keyActionMapping for clarity
- Fix ov.yaml: change toggle_mouse key from "ctrl+f3" to "ctrl+F4" to resolve duplicate binding issue
This ensures more robust key binding validation and helps users identify and fix configuration issues more effectively.

Fix duplicate key binding detection with proper normalization
